/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "stm32f103x8_EXTI_driver.h"
#include "stm32f103x8_RCC_driver.h"
#include "stm32f103x8_USART_driver.h"
#include "stm32f103x8_SPI_driver.h"

#include "lcd.h"
#include "keypad.h"


#define MCU_ACT_AS_MASTER
#define MCU_ACT_AS_SLAVE


unsigned int IRQ_Flag = 0 ;
unsigned char ch ;


void SPI_IRQ_CallBack(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_ACT_AS_SLAVE
	if(irq_src.RXNE)
	{
		ch = 0xF;
		MCAL_SPI_SendReceive_Data(SPI1, &ch, Polling_DISABLE);
		MCAL_UART_SendData(USART1, &ch, enable);
	}
#endif

}




void Mohamed_UART_IRQ_Callback (struct UART_IRQ_Event* flag)
{

#ifdef MCU_ACT_AS_MASTER
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);

	// send to SPI
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_SendReceive_Data(SPI1, &ch, Polling_ENABLE);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif
}

void clock_INIT()
{
	//Enable CLock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

int main(void)
{

	clock_INIT();

	UART_Config uartCFG ;

	//	=============================== UART INIT ===============================
	//	PA9		TX
	//	PA10	RX
	//	PA11 	CTS
	//	PA12	RTS
	uartCFG.BaudRate = UART_BaudRate_115200 ;
	uartCFG.HwFlowCtl = UART_HwFlowCtl_NONE ;
	uartCFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE ;
	uartCFG.P_IRQ_CallBack = Mohamed_UART_IRQ_Callback;
	uartCFG.Parity =UART_Parity__NONE ;
	uartCFG.Payload_Length = UART_Payload_Length_8B;
	uartCFG.StopBits = UART_StopBits__1 ;
	uartCFG.USART_Mode = UART_MODE_TX_RX ;

	MCAL_UART_Init(USART1, &uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);



	//	=============================== SPI INIT ===============================
	//	PA4		SPI1_NSS
	//	PA5		SPI1_SCK
	//	PA6 	SPI1_MISO
	//	PA7		SPI1_MOSI
	SPI_Config_t SPI1_Config;

	// Common Configuration
	SPI1_Config.CLKPhase = SPI_Clock_Second_Edge_Capture;
	SPI1_Config.CLKPolarity = SPI_Clock_Polarity_High_Idle;
	SPI1_Config.Data_Size = SPI_Size_8bit;
	SPI1_Config.Frame_Format = SPI_MSB_First;
	// Assume defaut PCLK2 is 8 MHZ
	SPI1_Config.SPI_BAUDRATE_PRESCALER = SPI_Prescaler_8;
	SPI1_Config.Communication_Mode = SPI_Communication_2_Lines_Full_Duplex;

#ifdef MCU_ACT_AS_MASTER
	SPI1_Config.Device_Mode = SPI_DEVICE_Mode_Master;
	SPI1_Config.IRQ_Enable = SPI_IRQ_Enable_NONE;
	SPI1_Config.NSS = SPI_NSS_SW_Set;
	SPI1_Config.P_IRQ_CallBack = NULL;

	// configure SS on portA pin4 by GPIO
	PinCfg.GPIO_PinNumber  = 4;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA , &PinCfg);


	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif


#ifdef MCU_ACT_AS_SLAVE
	SPI1_Config.Device_Mode = SPI_DEVICE_Mode_Slave;
	SPI1_Config.IRQ_Enable = SPI_IRQ_Enable_RXNEIE;
	SPI1_Config.NSS = SPI_NSS_Hard_Slave;
	SPI1_Config.P_IRQ_CallBack = SPI_IRQ_CallBack;
#endif

	MCAL_SPI_init(SPI1, &SPI1_Config);
	MCAL_SPI_GPIO_SetPins(SPI1);




	/* Loop forever */
	while(1)
	{
	}

}
