/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103x6.h"

void Clock_INIT(){
	//	Enable Clock GPIO A
	RCC_GPIOA_CLK_EN();

	//	Enable Clock GPIO B
	RCC_GPIOB_CLK_EN();
}

void GPIO_INIT(){

	GPIO_PinConfig_t PinCFG;

	/*PA_1 as floating input*/
	PinCFG.GPIO_PinNumber = GPIO_PIN_1;
	PinCFG.GPIO_Mode = GPIO_MODE_INPUT_FLo;
	MCAL_GPIO_INIT(GPIOA, &PinCFG);

	/*PA_13 as floating input*/
	PinCFG.GPIO_PinNumber = GPIO_PIN_13;
	PinCFG.GPIO_Mode = GPIO_MODE_INPUT_FLo;
	MCAL_GPIO_INIT(GPIOA, &PinCFG);




	/*PB_1 as push pull output*/
	PinCFG.GPIO_PinNumber = GPIO_PIN_1;
	PinCFG.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_Output_Speed = GPIO_SPEED_10_MHZ;
	MCAL_GPIO_INIT(GPIOB, &PinCFG);



	/*PB_1 as push pull output*/
	PinCFG.GPIO_PinNumber = GPIO_PIN_13;
	PinCFG.GPIO_Mode = GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_Output_Speed = GPIO_SPEED_10_MHZ;
	MCAL_GPIO_INIT(GPIOB, &PinCFG);





}

void wait_ms(volatile unsigned int time){
	volatile unsigned int i, j;
	for(i = 0; i< time ; i++)
		for(j = 0; j < 255 ; j++);
}


int main(void)
{
	Clock_INIT();
	GPIO_INIT();


	while(1){
		if (MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0)
		{
			MCAL_GPIO_TogglePIN(GPIOA, GPIO_PIN_1);
			while (MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_1) == 0);
		}
		if (MCAL_GPIO_ReadPIN(GPIOA, GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_TogglePIN(GPIOA, GPIO_PIN_13);
		}
		wait_ms(1);
	}

	return 0;
}








